### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by zhaoyangxihui** [robertlevonyan/CameraXDemo#6]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2282)
        at androidx.camera.core.VideoCapture.audioEncode(VideoCapture.java:753)
        at androidx.camera.core.VideoCapture$1.run(VideoCapture.java:372)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)

Similar question reference：[https://stackoverflow.com/questions/59613877/fatal-exception-camerax-audio-encoding-thread](url)

**Comment by robertlevonyan** [comment]
The demo project is updated. Please check it.
